# Site settings
title: "5im0nzy"
email: simony503@gmail.com
description: "Feel free to email me."
baseurl: ""
url: "http://yzh503.github.io"
title_description: "Ramblings of computer science, software development, algorithms, web penetration test... maybe some other interesting stuff. It's a long way from scientific theory to engineered product."
title_image: "https://en.gravatar.com/userimage/92928099/2795b51533a1beab5b4dfe39ae6b255b.jpg?size=200"
github_repository: https://github.com/yzh503 
disqus_account: simonzihaoyang
post_limit: 5

# Social usernames/URLs
github_username: yzh503
facebook_link: yzh503
stackoverflow_link: http://stackexchange.com/users/5706748/simon-zihao-yang/

# Footer
footer_left: "Thanks <a href=\"https://twitter.com/_JacobTomlinson\">Jacob</a> for the amazing theme"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/yzh503\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
