# Site settings
title: 5im0nzy 
email: simony503@gmail.com
description: > 
  Knowing more is less. 
baseurl: "" 
url: "http://yzh503.github.io" # the base hostname & protocol for your site
github_username: yzh503

# Build settings
markdown: kramdown
