# Site settings
title: "Simon Yzh"
email: yzh503@live.com
description: "Feel free to email me."
baseurl: ""
url: "http://yzh503.github.io"
title_description: "Ramblings about computer science, software development, algorithms, security... and some other interesting stuff."
title_image: "/Logo.jpg"
disqus_account: yzh503githubio
twitter_username: zyan503
github_repository: https://github.com/yzh503
addthis_id: ra-55d5952a46bf3aa2
post_limit: 5

# Social usernames/URLs
github_username: yzh503
facebook_link: yzh503
stackoverflow_link: http://stackoverflow.com/users/4509985/

# Footer
footer_left: "Theme derived from <a href=\"http://jekyllthemes.org/themes/carte-noire\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/yzh503\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
highlighter: rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
gems:
  - jekyll-feed
exclude: [vendor]
exclude:
  - Gemfile
  - Gemfile.lock
